keyconfig_version = (4, 0, 36)
keyconfig_data = \
[("3D View",
  {"space_type": 'VIEW_3D', "region_type": 'WINDOW'},
  {"items":
   [("view3d.cursor3d", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("transform.translate",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True},
     {"properties":
      [("cursor_transform", True),
       ("release_confirm", True),
       ],
      },
     ),
    ("view3d.localview", {"type": 'NUMPAD_SLASH', "value": 'PRESS'}, None),
    ("view3d.localview", {"type": 'SLASH', "value": 'PRESS'}, None),
    ("view3d.localview", {"type": 'MOUSESMARTZOOM', "value": 'ANY'}, None),
    ("view3d.localview_remove_from", {"type": 'NUMPAD_SLASH', "value": 'PRESS', "alt": True}, None),
    ("view3d.localview_remove_from", {"type": 'SLASH', "value": 'PRESS', "alt": True}, None),
    ("view3d.rotate", {"type": 'LEFTMOUSE', "value": 'ANY', "alt": True}, None),
    ("view3d.rotate", {"type": 'MIDDLEMOUSE', "value": 'PRESS'}, None),
    ("view3d.move", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "alt": True}, None),
    ("view3d.rotate", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("view3d.move", {"type": 'TRACKPADPAN', "value": 'ANY', "shift": True}, None),
    ("view3d.zoom", {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True}, None),
    ("view3d.dolly", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'NUMPAD_PERIOD', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_all_regions", True),
       ],
      },
     ),
    ("view3d.view_selected",
     {"type": 'NUMPAD_PERIOD', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.smoothview", {"type": 'TIMER1', "value": 'ANY', "any": True}, None),
    ("view3d.zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("view3d.zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("view3d.zoom",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'EQUAL', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'MINUS', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELINMOUSE', "value": 'PRESS'},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELOUTMOUSE', "value": 'PRESS'},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'EQUAL', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'MINUS', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.view_center_camera", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_center_lock", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS'},
     {"properties":
      [("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_all_regions", True),
       ("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("center", True),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_view_pie'),
       ],
      },
     ),
    ("view3d.navigate", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "shift": True}, None),
    ("view3d.view_camera", {"type": 'NUMPAD_0', "value": 'PRESS'}, None),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_2', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITDOWN'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_4', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITLEFT'),
       ],
      },
     ),
    ("view3d.view_persportho", {"type": 'NUMPAD_5', "value": 'PRESS'}, None),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_6', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_8', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITUP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANDOWN'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANLEFT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_6', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANRIGHT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_8', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANUP'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_6', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_9', "value": 'PRESS'},
     {"properties":
      [("angle", 3.1415927),
       ("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'FRONT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'TOP'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'BACK'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'LEFT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'BOTTOM'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'MIDDLEMOUSE', "value": 'CLICK_DRAG', "alt": True, "direction": 'NORTH'},
     {"properties":
      [("type", 'TOP'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'MIDDLEMOUSE', "value": 'CLICK_DRAG', "alt": True, "direction": 'SOUTH'},
     {"properties":
      [("type", 'BOTTOM'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'MIDDLEMOUSE', "value": 'CLICK_DRAG', "alt": True, "direction": 'EAST'},
     {"properties":
      [("type", 'RIGHT'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'MIDDLEMOUSE', "value": 'CLICK_DRAG', "alt": True, "direction": 'WEST'},
     {"properties":
      [("type", 'LEFT'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_center_pick", {"type": 'MIDDLEMOUSE', "value": 'CLICK', "alt": True}, None),
    ("view3d.ndof_orbit_zoom", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("view3d.ndof_orbit", {"type": 'NDOF_MOTION', "value": 'ANY', "ctrl": True}, None),
    ("view3d.ndof_pan", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True}, None),
    ("view3d.ndof_all", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CW', "value": 'PRESS'},
     {"properties":
      [("angle", 1.5707964),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CCW', "value": 'PRESS'},
     {"properties":
      [("angle", -1.5707964),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_BACK', "value": 'PRESS'},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_LEFT', "value": 'PRESS'},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_BOTTOM', "value": 'PRESS'},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'FRONT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'TOP'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("center", True),
       ("object", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("toggle", True),
       ("center", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True, "alt": True},
     {"properties":
      [("center", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("toggle", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("toggle", True),
       ("center", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("view3d.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("view3d.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("view3d.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("view3d.clip_border", {"type": 'B', "value": 'PRESS', "alt": True}, None),
    ("view3d.zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ("view3d.render_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.clear_render_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.camera_to_view", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.object_as_camera", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.copybuffer", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.pastebuffer", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'TAB', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.use_snap'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_PT_snapping'),
       ("keep_open", True),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_snap_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.show_gizmo'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_pivot_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'COMMA', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_orientations_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'Z', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_shading_pie'),
       ],
      },
     ),
    ("view3d.toggle_shading",
     {"type": 'Z', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'WIREFRAME'),
       ],
      },
     ),
    ("view3d.toggle_xray", {"type": 'Z', "value": 'PRESS', "alt": True}, None),
    ("wm.context_toggle",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.show_overlays'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.select_box'),
       ("cycle", True),
       ],
      },
     ),
    ],
   },
  ),
 ("3D View Generic",
  {"space_type": 'VIEW_3D', "region_type": 'WINDOW'},
  {"items":
   [("wm.context_toggle",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.show_region_toolbar'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.show_region_ui'),
       ],
      },
     ),
    ],
   },
  ),
 ("Dopesheet",
  {"space_type": 'DOPESHEET_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("column", True),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ("column", True),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("channel", True),
       ],
      },
     ),
    ("action.clickselect",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("extend", True),
       ("channel", True),
       ],
      },
     ),
    ("action.select_leftright",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("mode", 'CHECK'),
       ],
      },
     ),
    ("action.select_leftright",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'CHECK'),
       ("extend", True),
       ],
      },
     ),
    ("action.select_leftright",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("mode", 'LEFT'),
       ],
      },
     ),
    ("action.select_leftright",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("mode", 'RIGHT'),
       ],
      },
     ),
    ("action.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("action.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("action.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("action.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("action.select_box",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("axis_range", False),
       ],
    "active":False,
      },
     ),
    ("action.select_box",
     {"type": 'B', "value": 'PRESS', "alt": True},
     {"properties":
      [("axis_range", True),
       ],
      },
     ),
    ("action.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("mode", 'SET'),
       ("tweak", True),
       ],
      },
     ),
    ("action.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "shift": True},
     {"properties":
      [("mode", 'ADD'),
       ("tweak", True),
       ],
      },
     ),
    ("action.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ("tweak", True),
       ],
      },
     ),
    ("action.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("action.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("action.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("action.select_column",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("mode", 'KEYS'),
       ],
      },
     ),
    ("action.select_column",
     {"type": 'K', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'CFRA'),
       ],
      },
     ),
    ("action.select_column",
     {"type": 'K', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'MARKERS_COLUMN'),
       ],
      },
     ),
    ("action.select_column",
     {"type": 'K', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'MARKERS_BETWEEN'),
       ],
      },
     ),
    ("action.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("action.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("action.select_linked", {"type": 'L', "value": 'PRESS'}, None),
    ("action.frame_jump", {"type": 'G', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'DOPESHEET_MT_snap_pie'),
       ],
      },
     ),
    ("action.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("action.handle_type", {"type": 'V', "value": 'PRESS'}, None),
    ("action.interpolation_type", {"type": 'T', "value": 'PRESS'}, None),
    ("action.extrapolation_type", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("action.easing_type", {"type": 'E', "value": 'PRESS', "ctrl": True}, None),
    ("action.keyframe_type", {"type": 'R', "value": 'PRESS'}, None),
    ("action.bake_keys", {"type": 'O', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'DOPESHEET_MT_delete'),
       ],
      },
     ),
    ("action.delete",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("confirm", False),
       ],
      },
     ),
    ("action.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("action.keyframe_insert", {"type": 'I', "value": 'PRESS'}, None),
    ("action.copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("action.paste", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("action.paste",
     {"type": 'V', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("flipped", True),
       ],
      },
     ),
    ("action.previewrange_set", {"type": 'P', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("action.view_all", {"type": 'HOME', "value": 'PRESS'}, None),
    ("action.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("action.view_selected", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("action.view_frame", {"type": 'NUMPAD_0', "value": 'PRESS'}, None),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'DOPESHEET_MT_view_pie'),
       ],
      },
     ),
    ("anim.channels_editable_toggle", {"type": 'TAB', "value": 'PRESS'}, None),
    ("anim.channels_select_filter", {"type": 'F', "value": 'PRESS', "ctrl": True}, None),
    ("transform.transform",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("mode", 'TIME_TRANSLATE'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("mode", 'TIME_TRANSLATE'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("mode", 'TIME_EXTEND'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS'},
     {"properties":
      [("mode", 'TIME_SCALE'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'T', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'TIME_SLIDE'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_action'),
       ],
      },
     ),
    ("marker.add", {"type": 'M', "value": 'PRESS'}, None),
    ("marker.camera_bind", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'DOPESHEET_MT_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'DOPESHEET_MT_context_menu'),
       ],
      },
     ),
    ("anim.change_frame", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True}, None),
    ],
   },
  ),
 ("Image",
  {"space_type": 'IMAGE_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("image.view_all", {"type": 'HOME', "value": 'PRESS'}, None),
    ("image.view_all",
     {"type": 'HOME', "value": 'PRESS', "shift": True},
     {"properties":
      [("fit_view", True),
       ],
      },
     ),
    ("image.view_selected", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("image.view_cursor_center", {"type": 'C', "value": 'PRESS', "shift": True}, None),
    ("image.view_pan", {"type": 'LEFTMOUSE', "value": 'PRESS', "alt": True}, None),
    ("image.view_pan", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "alt": True}, None),
    ("image.view_pan", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("image.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("image.view_ndof", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("image.view_zoom_in", {"type": 'WHEELINMOUSE', "value": 'PRESS'}, None),
    ("image.view_zoom_out", {"type": 'WHEELOUTMOUSE', "value": 'PRESS'}, None),
    ("image.view_zoom_in", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "repeat": True}, None),
    ("image.view_zoom_out", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "repeat": True}, None),
    ("image.view_zoom", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("image.view_zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("image.view_zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("image.view_zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 8.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 4.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 2.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 8.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 4.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 2.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_1', "value": 'PRESS'},
     {"properties":
      [("ratio", 1.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.5),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.25),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.125),
       ],
      },
     ),
    ("image.change_frame", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("image.sample", {"type": 'RIGHTMOUSE', "value": 'PRESS'}, None),
    ("image.curves_point_set",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("point", 'BLACK_POINT'),
       ],
      },
     ),
    ("image.curves_point_set",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("point", 'WHITE_POINT'),
       ],
      },
     ),
    ("object.mode_set",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("mode", 'EDIT'),
       ("toggle", True),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 0),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 1),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 2),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'FOUR', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 3),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'FIVE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 4),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'SIX', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 5),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'SEVEN', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 6),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'EIGHT', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 7),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'NINE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 8),
       ],
      },
     ),
    ("image.render_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("image.clear_render_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("wm.context_toggle",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.show_gizmo'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.show_overlays'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'IMAGE_MT_mask_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'IMAGE_MT_mask_context_menu'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("name", 'IMAGE_MT_pivot_pie'),
       ],
      },
     ),
    ("image.view_zoom", {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "alt": True}, None),
    ],
   },
  ),
 ("Markers",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("marker.add", {"type": 'M', "value": 'PRESS'}, None),
    ("marker.move",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("tweak", True),
       ],
      },
     ),
    ("marker.duplicate", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("marker.select", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("marker.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("marker.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("camera", True),
       ],
      },
     ),
    ("marker.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ("camera", True),
       ],
      },
     ),
    ("marker.select_box",
     {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'},
     {"properties":
      [("tweak", True),
       ],
      },
     ),
    ("marker.select_box",
     {"type": 'Q', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("marker.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("marker.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("marker.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("marker.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("marker.delete", {"type": 'X', "value": 'PRESS'}, None),
    ("marker.delete",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("confirm", False),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'F2', "value": 'PRESS'},
     {"properties":
      [("name", 'TOPBAR_PT_name_marker'),
       ("keep_open", False),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("name", 'TOPBAR_PT_name_marker'),
       ("keep_open", False),
       ],
      },
     ),
    ("marker.move", {"type": 'G', "value": 'PRESS'}, None),
    ("marker.camera_bind", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ],
   },
  ),
 ("Mesh",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("transform.translate", {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'}, None),
    ("transform.translate",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("alt_navigation", True),
       ],
      },
     ),
    ("transform.rotate",
     {"type": 'R', "value": 'PRESS'},
     {"properties":
      [("alt_navigation", True),
       ],
      },
     ),
    ("transform.resize",
     {"type": 'S', "value": 'PRESS'},
     {"properties":
      [("alt_navigation", True),
       ],
      },
     ),
    ("transform.bend", {"type": 'W', "value": 'PRESS', "shift": True}, None),
    ("transform.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("transform.tosphere", {"type": 'S', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("transform.skin_resize", {"type": 'A', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.loopcut_slide",
     {"type": 'R', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("TRANSFORM_OT_edge_slide",
        [("release_confirm", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.offset_edge_loops_slide",
     {"type": 'R', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("TRANSFORM_OT_edge_slide",
        [("release_confirm", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.inset", {"type": 'I', "value": 'PRESS'}, None),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("affect", 'EDGES'),
       ],
      },
     ),
    ("transform.shrink_fatten", {"type": 'S', "value": 'PRESS', "alt": True}, None),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("affect", 'VERTICES'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.loop_select", {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK', "alt": True}, None),
    ("mesh.loop_select",
     {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK', "shift": True, "alt": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("mesh.edgering_select", {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True, "alt": True}, None),
    ("mesh.edgering_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("use_fill", False),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("use_fill", True),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("mesh.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("mesh.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("mesh.select_next_item", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True}, None),
    ("mesh.select_prev_item", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True}, None),
    ("mesh.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("mesh.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("mesh.select_mirror", {"type": 'M', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_select_similar'),
       ],
      },
     ),
    ("mesh.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("mesh.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("mesh.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "shift": True},
     {"properties":
      [("inside", False),
       ],
      },
     ),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("inside", True),
       ],
      },
     ),
    ("view3d.edit_mesh_extrude_move_normal",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("alt_navigation", True),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_extrude'),
       ],
      },
     ),
    ("transform.edge_crease", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("mesh.fill", {"type": 'F', "value": 'PRESS', "alt": True}, None),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("quad_method", 'BEAUTY'),
       ("ngon_method", 'BEAUTY'),
       ],
      },
     ),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("quad_method", 'FIXED'),
       ("ngon_method", 'CLIP'),
       ],
      },
     ),
    ("mesh.tris_convert_to_quads", {"type": 'J', "value": 'PRESS', "alt": True}, None),
    ("mesh.rip_move",
     {"type": 'V', "value": 'PRESS'},
     {"properties":
      [("MESH_OT_rip",
        [("use_fill", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.rip_move",
     {"type": 'V', "value": 'PRESS', "alt": True},
     {"properties":
      [("MESH_OT_rip",
        [("use_fill", True),
         ],
        ),
       ],
      },
     ),
    ("mesh.rip_edge_move",
     {"type": 'D', "value": 'PRESS', "alt": True},
     {"properties":
      [("TRANSFORM_OT_translate",
        [("alt_navigation", True),
         ],
        ),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_merge'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_split'),
       ],
      },
     ),
    ("mesh.edge_face_add", {"type": 'F', "value": 'PRESS', "repeat": True}, None),
    ("mesh.duplicate_move",
     {"type": 'D', "value": 'PRESS', "shift": True},
     {"properties":
      [("TRANSFORM_OT_translate",
        [("alt_navigation", True),
         ],
        ),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_mesh_add'),
       ],
      },
     ),
    ("mesh.separate", {"type": 'P', "value": 'PRESS'}, None),
    ("mesh.split", {"type": 'Y', "value": 'PRESS'}, None),
    ("mesh.vert_connect_path", {"type": 'J', "value": 'PRESS'}, None),
    ("mesh.point_normals", {"type": 'L', "value": 'PRESS', "alt": True}, None),
    ("transform.vert_slide", {"type": 'V', "value": 'PRESS', "shift": True}, None),
    ("mesh.dupli_extrude_cursor",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("rotate_source", True),
       ],
      },
     ),
    ("mesh.dupli_extrude_cursor",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("rotate_source", False),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_delete'),
       ],
      },
     ),
    ("mesh.dissolve_mode", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.dissolve_mode", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.knife_tool",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("use_occlude_geometry", True),
       ("only_selected", False),
       ],
      },
     ),
    ("mesh.knife_tool",
     {"type": 'K', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_occlude_geometry", False),
       ("only_selected", True),
       ],
      },
     ),
    ("object.vertex_parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'F', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_faces'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_edges'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'V', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_vertices'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'H', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_hook'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'U', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_uv_map'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_vertex_group'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'N', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_normals'),
       ],
      },
     ),
    ("object.vertex_group_remove_from", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_connected'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Object Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit_objects'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("object.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("object.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("object.select_linked", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("object.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("object.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", False),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", True),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "repeat": True},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", False),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", True),
       ],
      },
     ),
    ("object.parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("object.parent_clear", {"type": 'P', "value": 'PRESS', "alt": True}, None),
    ("transform.translate", {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'}, None),
    ("transform.translate",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("alt_navigation", True),
       ],
      },
     ),
    ("transform.rotate",
     {"type": 'R', "value": 'PRESS'},
     {"properties":
      [("alt_navigation", True),
       ],
    "active":False,
      },
     ),
    ("transform.resize",
     {"type": 'S', "value": 'PRESS'},
     {"properties":
      [("alt_navigation", True),
       ],
      },
     ),
    ("transform.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("object.transform_axis_target", {"type": 'T', "value": 'PRESS', "shift": True}, None),
    ("object.location_clear",
     {"type": 'G', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.rotation_clear",
     {"type": 'R', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.scale_clear",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("use_global", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'X', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_global", True),
       ],
      },
     ),
    ("object.delete",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("use_global", False),
       ("confirm", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'DEL', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_global", True),
       ("confirm", False),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_add'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_object_apply'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'L', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_make_links'),
       ],
      },
     ),
    ("object.duplicate_move",
     {"type": 'D', "value": 'PRESS', "shift": True},
     {"properties":
      [("TRANSFORM_OT_translate",
        [("alt_navigation", True),
         ],
        ),
       ],
      },
     ),
    ("object.duplicate_move_linked",
     {"type": 'D', "value": 'PRESS', "alt": True},
     {"properties":
      [("TRANSFORM_OT_translate",
        [("alt_navigation", True),
         ],
        ),
       ],
      },
     ),
    ("object.join", {"type": 'J', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'PERIOD', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'tool_settings.use_transform_data_origin'),
       ],
      },
     ),
    ("anim.keyframe_insert_menu", {"type": 'I', "value": 'PRESS'}, None),
    ("anim.keyframe_delete_v3d", {"type": 'I', "value": 'PRESS', "alt": True}, None),
    ("anim.keying_set_active_set", {"type": 'I', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("collection.create", {"type": 'G', "value": 'PRESS', "ctrl": True}, None),
    ("collection.objects_remove", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("collection.objects_remove_all", {"type": 'G', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("collection.objects_add_active", {"type": 'G', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("collection.objects_remove_active", {"type": 'G', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("object.subdivision_set",
     {"type": 'ZERO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 0),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 1),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 2),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 3),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FOUR', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 4),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FIVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 5),
       ("relative", False),
       ],
      },
     ),
    ("object.move_to_collection", {"type": 'M', "value": 'PRESS'}, None),
    ("object.link_to_collection", {"type": 'M', "value": 'PRESS', "shift": True}, None),
    ("object.hide_view_clear", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("object.hide_view_set",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("object.hide_view_set",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("object.hide_collection", {"type": 'H', "value": 'PRESS', "ctrl": True}, None),
    ("object.hide_collection",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("collection_index", 1),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("collection_index", 2),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("collection_index", 3),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FOUR', "value": 'PRESS'},
     {"properties":
      [("collection_index", 4),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FIVE', "value": 'PRESS'},
     {"properties":
      [("collection_index", 5),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SIX', "value": 'PRESS'},
     {"properties":
      [("collection_index", 6),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SEVEN', "value": 'PRESS'},
     {"properties":
      [("collection_index", 7),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'EIGHT', "value": 'PRESS'},
     {"properties":
      [("collection_index", 8),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'NINE', "value": 'PRESS'},
     {"properties":
      [("collection_index", 9),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ZERO', "value": 'PRESS'},
     {"properties":
      [("collection_index", 10),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ONE', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 11),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'TWO', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 12),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'THREE', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 13),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FOUR', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 14),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FIVE', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 15),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SIX', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 16),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SEVEN', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 17),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'EIGHT', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 18),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'NINE', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 19),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ZERO', "value": 'PRESS', "alt": True},
     {"properties":
      [("collection_index", 20),
       ("extend", False),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ONE', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 1),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'TWO', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 2),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'THREE', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 3),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FOUR', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 4),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FIVE', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 5),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SIX', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 6),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SEVEN', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 7),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'EIGHT', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 8),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'NINE', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 9),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ZERO', "value": 'PRESS', "shift": True},
     {"properties":
      [("collection_index", 10),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ONE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 11),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'TWO', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 12),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'THREE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 13),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FOUR', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 14),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'FIVE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 15),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SIX', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 16),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'SEVEN', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 17),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'EIGHT', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 18),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'NINE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 19),
       ("extend", True),
       ],
      },
     ),
    ("object.hide_collection",
     {"type": 'ZERO', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("collection_index", 20),
       ("extend", True),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_object_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_object_context_menu'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.move'),
       ("cycle", True),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.rotate'),
       ("cycle", True),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'R', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.scale'),
       ("cycle", True),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'T', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.transform'),
       ("cycle", True),
       ],
      },
     ),
    ],
   },
  ),
 ("Toolbar Popup <temp>",
  {"space_type": 'EMPTY', "region_type": 'TEMPORARY'},
  {"items":
   [("wm.tool_set_by_id",
     {"type": 'SPACE', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.cursor'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.select'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.select_lasso'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'T', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.transform'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'M', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.measure'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'B', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.select_box'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'C', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.select_circle'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.move'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'R', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.rotate'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'S', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.scale'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.extrude_region'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'I', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.inset_faces'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'B', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'builtin.bevel'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'R', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'builtin.loop_cut'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'R', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'builtin.offset_edge_loop_cut'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.knife'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'V', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.vertex_slide'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'builtin.shrink_fatten'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("name", 'builtin.shear'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'S', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("name", 'builtin.to_sphere'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'V', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.rip_region'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'D', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'builtin.rip_edge'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'D', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.annotate'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.select'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_1', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.select'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.select_lasso'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_2', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.select_lasso'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.scale_cage'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_3', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.scale_cage'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'FOUR', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.transform'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_4', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.transform'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'FIVE', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.annotate_line'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_5', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.annotate_line'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'SIX', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.annotate_polygon'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_6', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.annotate_polygon'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'SEVEN', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.annotate_eraser'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_7', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.annotate_eraser'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'EIGHT', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.measure'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_8', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.measure'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NINE', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.primitive_cube_add'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_9', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.primitive_cube_add'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'ZERO', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.primitive_cone_add'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_0', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.primitive_cone_add'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'ONE', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.primitive_cylinder_add'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.primitive_cylinder_add'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'TWO', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.primitive_uv_sphere_add'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_2', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.primitive_uv_sphere_add'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'THREE', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.primitive_ico_sphere_add'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_3', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.primitive_ico_sphere_add'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'FOUR', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.extrude_manifold'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.extrude_manifold'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'FIVE', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.extrude_along_normals'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_5', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.extrude_along_normals'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'SIX', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.extrude_individual'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_6', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.extrude_individual'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'SEVEN', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.extrude_to_cursor'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_7', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.extrude_to_cursor'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'EIGHT', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.bisect'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_8', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.bisect'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NINE', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.poly_build'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_9', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.poly_build'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'ZERO', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.spin'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_0', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'builtin.spin'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'builtin.spin_duplicates'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_1', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'builtin.spin_duplicates'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'builtin.smooth'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'builtin.smooth'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'builtin.randomize'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_3', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'builtin.randomize'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'FOUR', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'builtin.edge_slide'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'builtin.edge_slide'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'FIVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'builtin.push_pull'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_5', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'builtin.push_pull'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'SPACE', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("name", 'builtin.cursor'),
       ],
      },
     ),
    ("ui.button_execute",
     {"type": 'SPACE', "value": 'RELEASE', "any": True},
     {"properties":
      [("skip_depressed", True),
       ],
      },
     ),
    ],
   },
  ),
 ("UV Editor",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu",
     {"type": 'TAB', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'IMAGE_MT_uvs_select_mode'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_extend", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_expand", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_extend", True),
       ("use_expand", True),
       ("type", 'FACE'),
       ],
      },
     ),
    ("mesh.select_mode", {"type": 'FOUR', "value": 'PRESS'}, None),
    ("uv.select_mode",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("type", 'VERTEX'),
       ],
      },
     ),
    ("uv.select_mode",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("type", 'EDGE'),
       ],
      },
     ),
    ("uv.select_mode",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("type", 'FACE'),
       ],
      },
     ),
    ("uv.select_mode",
     {"type": 'FOUR', "value": 'PRESS'},
     {"properties":
      [("type", 'ISLAND'),
       ],
      },
     ),
    ("uv.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("uv.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("uv.mark_seam", {"type": 'E', "value": 'PRESS', "ctrl": True}, None),
    ("uv.select_loop", {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK', "alt": True}, None),
    ("uv.select_loop",
     {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("uv.select_edge_ring", {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True, "alt": True}, None),
    ("uv.select_edge_ring",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("uv.shortest_path_pick",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("use_fill", False),
       ],
      },
     ),
    ("uv.shortest_path_pick",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("use_fill", True),
       ],
      },
     ),
    ("uv.select_split", {"type": 'Y', "value": 'PRESS'}, None),
    ("uv.select_box",
     {"type": 'B', "value": 'PRESS'},
     {"properties":
      [("pinned", False),
       ],
      },
     ),
    ("uv.select_box",
     {"type": 'B', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("pinned", True),
       ],
      },
     ),
    ("uv.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("uv.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("uv.select_lasso",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("uv.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("uv.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("extend", True),
       ("deselect", False),
       ],
      },
     ),
    ("uv.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("uv.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("uv.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("uv.select_similar", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("uv.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("uv.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("uv.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("uv.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("uv.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("uv.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("uv.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("uv.select_pinned", {"type": 'P', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS'},
     {"properties":
      [("name", 'IMAGE_MT_uvs_merge'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'IMAGE_MT_uvs_split'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'IMAGE_MT_uvs_align'),
       ],
      },
     ),
    ("uv.stitch", {"type": 'V', "value": 'PRESS', "alt": True}, None),
    ("uv.rip_move", {"type": 'V', "value": 'PRESS'}, None),
    ("uv.pin",
     {"type": 'P', "value": 'PRESS'},
     {"properties":
      [("clear", False),
       ],
      },
     ),
    ("uv.pin",
     {"type": 'P', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear", True),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'U', "value": 'PRESS'},
     {"properties":
      [("name", 'IMAGE_MT_uvs_unwrap'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'IMAGE_MT_uvs_snap_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit'),
       ],
      },
     ),
    ("transform.translate", {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'}, None),
    ("transform.translate",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("alt_navigation", True),
       ],
      },
     ),
    ("transform.rotate",
     {"type": 'R', "value": 'PRESS'},
     {"properties":
      [("alt_navigation", True),
       ],
      },
     ),
    ("transform.resize",
     {"type": 'S', "value": 'PRESS'},
     {"properties":
      [("alt_navigation", True),
       ],
      },
     ),
    ("transform.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("wm.context_toggle",
     {"type": 'TAB', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.use_snap_uv'),
       ],
      },
     ),
    ("wm.context_menu_enum",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("data_path", 'tool_settings.snap_uv_element'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.show_gizmo'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.show_overlays'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'IMAGE_MT_uvs_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'IMAGE_MT_uvs_context_menu'),
       ],
      },
     ),
    ("uv.cursor_set", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("transform.translate",
     {"type": 'RIGHTMOUSE', "value": 'CLICK_DRAG', "shift": True},
     {"properties":
      [("cursor_transform", True),
       ("release_confirm", True),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.select_box'),
       ("cycle", True),
       ],
      },
     ),
    ],
   },
  ),
 ]


if __name__ == "__main__":
    # Only add keywords that are supported.
    from bpy.app import version as blender_version
    keywords = {}
    if blender_version >= (2, 92, 0):
        keywords["keyconfig_version"] = keyconfig_version
    import os
    from bl_keymap_utils.io import keyconfig_import_from_data
    keyconfig_import_from_data(
        os.path.splitext(os.path.basename(__file__))[0],
        keyconfig_data,
        **keywords,
    )
